loki:
  storage:
    type: s3
    bucketNames:
      chunks: loki-logs
      ruler: loki-logs
      admin: loki-logs
    s3:
      endpoint: minio.minio.svc:9000
      region: us-east-1
      accessKeyId: minio
      secretAccessKey: minio-local-secret
      s3ForcePathStyle: true
      insecure: true
