apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/demo-shop-api.yaml
  - manifests/demo-blog-web.yaml
  - manifests/load-generator.yaml

commonLabels:
  demo: "true"
